### ISSUE TITLE
mDNS not working

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/vaani.setup#1]
It seems like the mDNS resolution is not working in all kinds of networks. At least within one network it was not possible resolving "vaani.local".

**Comment by davidflanagan** [comment]
Edison or RPi?  Was this while it was in AP mode or after leaving AP mode?

Did you follow all the config steps in the README?  In particular for Edison, did you install avahi and disable mdns?

**Comment by tilmankamp** [comment]
I used the Raspberry Pi path through the README. Sorry - forgot to mention that. Accessing vaani.local failed in both cases - for the AP and later (in our Guest network). I think the README should contain a step about changing ```/etc/hotstname```.
